name: social_app
description: Rede social mock Flutter MVC
publish_to: none
version: 1.0.0+1
environment:
  sdk: '^3.6.1'

dependencies:
  flutter:
    sdk: flutter
  mobx: ^2.2.0
  flutter_mobx: ^2.2.0+1
  provider: ^6.0.5
  dio: ^5.4.3+1
  sqflite: ^2.3.3+1
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.10
  mobx_codegen: ^2.6.1
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - mockup/users.json
    - mockup/posts.json